### ISSUE TITLE
Progress bar is broken for tarball files and docker images

### ISSUE THREAD

**Issue by marcosnils** [marcosnils/bin#11]
![image](https://user-images.githubusercontent.com/1578458/88212220-4adfd880-cc2d-11ea-944c-0134499ac813.png)

![image](https://user-images.githubusercontent.com/1578458/88212406-9a260900-cc2d-11ea-81a9-4626e0641907.png)

@arush-sal

**Comment by arush-sal** [comment]
@marcosnils I have an idea around why it is behaving this way but I'll take a deeper look into this tomorrow.

**Comment by arush-sal** [comment]
https://github.com/marcosnils/bin/blob/f0235857584c20f824d5f38013ea83827f590056/pkg/providers/github.go#L166-L173 

@marcosnils Since we are caching the whole file in the memory beforehand and then prompting the user for the file they want therefore the reported `Length` is smaller than the actual file length. For a fix, I can get the actual file name to be used for the `Length` but that still won't fix the transfer speed issue as the reported speed will actually just be the `memory` -> `disk` copy speed. WYT?

**Comment by sirlatrom** [comment]
Additionally, several archive formats require the entire file to be read before you can find the file you're looking for. Maybe it would be possible to always show the progress bar for the actual download (i.e. centre it around the http client somehow)?

**Comment by arush-sal** [comment]
@sirlatrom yeah even I liked the idea of showing the progress bar when downloading the archive itself rather than a silent in-memory cache, but I guess that design change is Marcos's call :sweat_smile:

**Comment by marcosnils** [comment]
> Maybe it would be possible to always show the progress bar for the actual download (i.e. centre it around the http client somehow)?

Yeah.. that's the idea :)
