### ISSUE TITLE
Change the tool name to binmgr

### ISSUE THREAD

**Issue by jJit0** [marcosnils/bin#112]
Hi,

I may suggest to change the tool name to binmgr or bin-manager or anything else, but not bin.

bin is very common in linux, it can refer to lots of things in linux.

**Comment by marcosnils** [comment]
> bin is very common in linux, it can refer to lots of things in linux.

can you provide some examples? I've searched in the most popular distro package managers (centos, arch, debian) and there's no `bin` package.

**Comment by jJit0** [comment]
No of course.
What I meant is bin refers mostly to a binary path. Tools usually have a complete name like binwalk or bingrep.

Your tool is awesome by the way, but its name means nothing, "bin what"

That's why binmgr, bin-manager, or bindl (bin downloader) has a meaning, it can even be added to debian repositories one day

**Comment by marcosnils** [comment]
> Your tool is awesome by the way, but its name means nothing, "bin what"

Thx!

I like the name because it's short, easy to type and no other tool is using it. Thanks for bringing up the idea but I don't have intentions to change unless several people request it since I personally find it comfortable to use. 

In any case, if you find it annoying, you can always create an alias. 

I'll close this since there's nothing else relevant to elaborate here.

**Comment by jJit0** [comment]
No problem, the alias idea is great

Thank you :)
