### ISSUE TITLE
Not working in Termux terminal app on Android 

### ISSUE THREAD

**Issue by edshamis** [marcosnils/bin#147]
I wanted to test bin in Termux terminal running on Android device. So I downloaded the latest release for Linux arm64 and got this error: 
```
  • Getting latest release for marcosnils/bin
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5eee18]

goroutine 1 [running]:
github.com/marcosnils/bin/pkg/providers.(*gitHub).Fetch(0x40003f4230, 0x40003f64c0)
	/home/marcos/Projects/bin/pkg/providers/github.go:39 +0x2c8
github.com/marcosnils/bin/cmd.newInstallCmd.func1(0x40000c58c0?, {0x400040a2a0?, 0x1?, 0x1?})
	/home/marcos/Projects/bin/cmd/install.go:65 +0x148
github.com/spf13/cobra.(*Command).execute(0x40000c58c0, {0x400040a280, 0x1, 0x1})
	/home/marcos/Projects/gopath/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x4dc
github.com/spf13/cobra.(*Command).ExecuteC(0x40000c5600)
	/home/marcos/Projects/gopath/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x358
github.com/spf13/cobra.(*Command).Execute(...)
	/home/marcos/Projects/gopath/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/marcosnils/bin/cmd.(*rootCmd).Execute(0x400000d3b0, {0x400001e190, 0x2, 0x400040a0e0?})
	/home/marcos/Projects/bin/cmd/root.go:35 +0x168
github.com/marcosnils/bin/cmd.Execute({0x400007a230, 0x6b}, 0x955e00?, {0x400001e190, 0x2, 0x2})
	/home/marcos/Projects/bin/cmd/root.go:25 +0xd4
main.main()
	/home/marcos/Projects/bin/main.go:21 +0xd0
```

`uname -a` output:
```
Linux localhost 4.14.180-perf-ge2a1322887a5 #1 SMP PREEMPT Mon Mar 28 19:47:44 CST 2022 aarch64 Android
```

Can you compile for aarch64 Android as well? I thought Linux arm64 would do but probably it doesn't

**Comment by marcosnils** [comment]
:wave: have you tried compiling to aarch64 manually to see if it'll work before pushing the change upstream?

**Comment by edshamis** [comment]
Please instruct me and I'll do it. 
Btw I managed to install bin through go: `go install github.com/marcosnils/bin@latest`, maybe you'd like to add it to readme

**Comment by edshamis** [comment]
This one worked `CGO_ENABLED=0 GOOS=android GOARCH=arm64 go build`

**Comment by yozachar** [comment]
Can an aarch64 build be released on GitHub?

**Comment by marcosnils** [comment]
> Can an aarch64 build be released on GitHub?

sure,c oming out in a bit.

**Comment by marcosnils** [comment]
done!: https://github.com/marcosnils/bin/releases/tag/v0.19.1

**Comment by einarpersson** [comment]
@marcosnils 
Hi! I too wanted to use this `bin` on my android phone in temux. Would it be possible to add an `android_arm64` release asset? I see this issue is closed but I could not get it working with the existing release assets.

I could get it to work when building from source with `CGO_ENABLED=1 GOOS=android GOARCH=arm64` with the NDK clang (`aarch64-linux-android24-clang`).

A `CGO_ENABLED=0` build **fails** in Termux with "lookup api.github.com on ::1:53: connection refused". I dont know, but my dear ai-assistant said it was becauseAndroid has no `/etc/resolv.conf`. I'm not knowledgeable enough to know if the NDK is truly necessary or if there is some other code change/work-around that would make it more cross-platform.

Would be great to get an android build working!

**Comment by marcosnils** [comment]
@einarpersson done in v0.29.4
