### ISSUE TITLE
Idea: Extract static binary from docker image

### ISSUE THREAD

**Issue by sirlatrom** [marcosnils/bin#30]
A few projects don't release binaries but do release docker images. If it's a static standalone binary and it's on the PATH of a given docker image, we could potentially copy out the binary from the image.

**Comment by marcosnils** [comment]
If we still have to download the image to do that.. why not still using the current docker support? I think it's going to be a bit difficult to know which docker images have only static binaries or could also potentially have a specific version of a lib and a dynamically compiled binary as well. 

We could add a logic to see if the binary inside the docker image is dynamic or static and extract it, but not sure how common that use case will be TBH... Since everyone pretty much have docker nowadays my take on this is to keep using the current docker support. 

Eventually, when/if people stops installing docker for some reason on their computers we can re-evaluate this and find the way to extract the binary of the image without actually having to depend on docker. 

Thoughts?

**Comment by sirlatrom** [comment]
I agree with your observations, it probably isn't the thing the user would expect anyway.
