### ISSUE TITLE
Bug: bin install github.com/Shopify/ejson creates ~/bin/linux

### ISSUE THREAD

**Issue by breml** [marcosnils/bin#68]
The releases of https://github.com/Shopify/ejson are not optimally named and therefore, bin creates `~/bin/linux` where I would like to get `~/bin/ejson`.

**Comment by breml** [comment]
Same problem with https://github.com/Shopify/ejson2env

**Comment by sirlatrom** [comment]
@marcosnils Should we support this scenario, i.e. the binary's name and the basename of the URL contain 0 occurrences of the repo's name, and in that case replace it with the repo's name?

**Comment by marcosnils** [comment]
> Should we support this scenario, i.e. the binary's name and the basename of the URL contain 0 occurrences of the repo's name, and in that case replace it with the repo's name?

Hmm I'm not sure about trying to be smart about this if package maintainers are not publishing their releases in a "readable way" . That was why I added `bin install <repo> [filename]` so in this case you can do `bin install https://github.com/Shopify/ejson ~/bin/ejson`. 

One thing that can be improved about the above example is that if you don't specify a path, to automatically put it in your `bin` configured path. If you do `bin install <url> somebinary` it'll put `somebinary ` in your current path instead. I guess that in order to achieve that, you can just do `bin install <url> ./somebinary`

Summary:  I'm not convinced to add something that ultimately should be the upstream repo to fix, since opening an issue in the original repository so the project fixes their package names should be right thing to do in the first place. In that sense we're implementing a "temporary" fix for something that's fundamentally wrong in the first place.

**Comment by sirlatrom** [comment]
@marcosnils I agree, and since the binary will keep its name in your `~/bin` folder (or wherever you chose to install it the first time), it is only a concern at the first install, until the upstream repo fixes their released asset names 😄

**Comment by marcosnils** [comment]
> @marcosnils I agree, and since the binary will keep its name in your `~/bin` folder (or wherever you chose to install it the first time), it is only a concern at the first install, until the upstream repo fixes their released asset names

Yep. @breml WDYT?

I'll try to find the time to fix the install path issue mentioned in my previous comment :)

**Comment by breml** [comment]
In general I agree, I successfully installed ejson2env with the following command: `bin install github.com/Shopify/ejson2env ~/bin/ejson2env`.

The thing I don't like about the current behavior is, that normally when I install a binary with `bin`, I do not necessarily check the content of the releases on the release page before. So I just try `bin install <github-url>`. With the current behavior I need to check the output of the command carefully, if this produces the expected binary name in my default bin directory.

At least some sort of warning would be nice.

**Comment by marcosnils** [comment]
> The thing I don't like about the current behavior is, that normally when I install a binary with `bin`, I do not necessarily check the content of the releases on the release page before. So I just try `bin install <github-url>`

yes, same. But when I see that the options that I get are very bad, I abort the install and re-install it using a custom binary name,

**Comment by breml** [comment]
The thing is, that for this particular binary you do not get any options at all.

**Comment by marcosnils** [comment]
> The thing is, that for this particular binary you do not get any options at all.

Oh, got it.. I also don't think it's that bad either, since `bin` will print the binary name after it's done downloading it. 

![image](https://user-images.githubusercontent.com/1578458/111913621-c2c90180-8a4d-11eb-9eab-a32e9419a049.png)

I think the message is quite clear, and this doesn't/shouldn't happen often. Not sure what's left to be done here.

**Comment by breml** [comment]
You might be right, there is not much `bin` can do about this. I close this issue.
